
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE TYPE "public"."TextLineType" AS ENUM (
    'TITLE',
    'DESCRIPTION',
    'TEXT',
    'REMARK'
);

ALTER TYPE "public"."TextLineType" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."dua_has_tags" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "dua_id" bigint NOT NULL,
    "tag_id" bigint NOT NULL
);

ALTER TABLE "public"."dua_has_tags" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."dua_translation_lines" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "dua_translation_id" bigint NOT NULL,
    "line_number" bigint NOT NULL,
    "text" "text" NOT NULL
);

ALTER TABLE "public"."dua_translation_lines" OWNER TO "postgres";

ALTER TABLE "public"."dua_translation_lines" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."dua_translation_lines_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."dua_translations" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "dua_id" bigint NOT NULL,
    "language" "text" NOT NULL,
    "source_id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "description" "text"
);

ALTER TABLE "public"."dua_translations" OWNER TO "postgres";

ALTER TABLE "public"."dua_translations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."dua_translations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."duas" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "route_name" "text" NOT NULL
);

ALTER TABLE "public"."duas" OWNER TO "postgres";

ALTER TABLE "public"."duas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."duas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."languages" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "name" "text" NOT NULL,
    "code" "text" NOT NULL
);

ALTER TABLE "public"."languages" OWNER TO "postgres";

ALTER TABLE "public"."languages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."languages_code_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."sources" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "name" "text" NOT NULL,
    "url" "text" NOT NULL
);

ALTER TABLE "public"."sources" OWNER TO "postgres";

COMMENT ON TABLE "public"."sources" IS 'Book author link to duas.org, ...';

ALTER TABLE "public"."sources" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."reference_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tags" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "name" "text" NOT NULL
);

ALTER TABLE "public"."tags" OWNER TO "postgres";

ALTER TABLE "public"."tags" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tags_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."text" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "route_name" "text"
);

ALTER TABLE "public"."text" OWNER TO "postgres";

ALTER TABLE "public"."text" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."text_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."text_line" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "text_id" bigint NOT NULL,
    "line_number" bigint NOT NULL,
    "type" "public"."TextLineType",
    "ar" "text",
    "tx" "text",
    "en" "text",
    "de" "text",
    "es" "text",
    "fr" "text",
    "it" "text",
    "tr" "text",
    "fa" "text",
    "ur" "text"
);

ALTER TABLE "public"."text_line" OWNER TO "postgres";

ALTER TABLE ONLY "public"."dua_has_tags"
    ADD CONSTRAINT "dua_has_tags_pkey" PRIMARY KEY ("dua_id", "tag_id");

ALTER TABLE ONLY "public"."dua_translation_lines"
    ADD CONSTRAINT "dua_translation_lines_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."dua_translations"
    ADD CONSTRAINT "dua_translations_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."duas"
    ADD CONSTRAINT "duas_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."duas"
    ADD CONSTRAINT "duas_route_name_key" UNIQUE ("route_name");

ALTER TABLE ONLY "public"."languages"
    ADD CONSTRAINT "languages_code_key" UNIQUE ("code");

ALTER TABLE ONLY "public"."languages"
    ADD CONSTRAINT "languages_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."sources"
    ADD CONSTRAINT "reference_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."text_line"
    ADD CONSTRAINT "text_line_pkey" PRIMARY KEY ("text_id", "line_number");

ALTER TABLE ONLY "public"."text"
    ADD CONSTRAINT "text_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."dua_has_tags"
    ADD CONSTRAINT "dua_has_tags_dua_id_fkey" FOREIGN KEY ("dua_id") REFERENCES "public"."duas"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."dua_has_tags"
    ADD CONSTRAINT "dua_has_tags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."dua_translation_lines"
    ADD CONSTRAINT "dua_translation_lines_dua_translation_id_fkey" FOREIGN KEY ("dua_translation_id") REFERENCES "public"."dua_translations"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."dua_translations"
    ADD CONSTRAINT "dua_translations_dua_id_fkey" FOREIGN KEY ("dua_id") REFERENCES "public"."duas"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."dua_translations"
    ADD CONSTRAINT "dua_translations_source_id_fkey" FOREIGN KEY ("source_id") REFERENCES "public"."sources"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."text_line"
    ADD CONSTRAINT "text_line_text_id_fkey" FOREIGN KEY ("text_id") REFERENCES "public"."text"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."dua_has_tags" TO "anon";
GRANT ALL ON TABLE "public"."dua_has_tags" TO "authenticated";
GRANT ALL ON TABLE "public"."dua_has_tags" TO "service_role";

GRANT ALL ON TABLE "public"."dua_translation_lines" TO "anon";
GRANT ALL ON TABLE "public"."dua_translation_lines" TO "authenticated";
GRANT ALL ON TABLE "public"."dua_translation_lines" TO "service_role";

GRANT ALL ON SEQUENCE "public"."dua_translation_lines_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."dua_translation_lines_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."dua_translation_lines_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."dua_translations" TO "anon";
GRANT ALL ON TABLE "public"."dua_translations" TO "authenticated";
GRANT ALL ON TABLE "public"."dua_translations" TO "service_role";

GRANT ALL ON SEQUENCE "public"."dua_translations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."dua_translations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."dua_translations_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."duas" TO "anon";
GRANT ALL ON TABLE "public"."duas" TO "authenticated";
GRANT ALL ON TABLE "public"."duas" TO "service_role";

GRANT ALL ON SEQUENCE "public"."duas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."duas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."duas_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."languages" TO "anon";
GRANT ALL ON TABLE "public"."languages" TO "authenticated";
GRANT ALL ON TABLE "public"."languages" TO "service_role";

GRANT ALL ON SEQUENCE "public"."languages_code_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."languages_code_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."languages_code_seq" TO "service_role";

GRANT ALL ON TABLE "public"."sources" TO "anon";
GRANT ALL ON TABLE "public"."sources" TO "authenticated";
GRANT ALL ON TABLE "public"."sources" TO "service_role";

GRANT ALL ON SEQUENCE "public"."reference_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."reference_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."reference_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tags" TO "anon";
GRANT ALL ON TABLE "public"."tags" TO "authenticated";
GRANT ALL ON TABLE "public"."tags" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."text" TO "anon";
GRANT ALL ON TABLE "public"."text" TO "authenticated";
GRANT ALL ON TABLE "public"."text" TO "service_role";

GRANT ALL ON SEQUENCE "public"."text_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."text_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."text_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."text_line" TO "anon";
GRANT ALL ON TABLE "public"."text_line" TO "authenticated";
GRANT ALL ON TABLE "public"."text_line" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
