create table "public"."dua_has_tags" (
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "dua_id" bigint not null,
    "tag_id" bigint not null
);


alter table "public"."dua_has_tags" enable row level security;

create table "public"."dua_infos" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "dua_id" bigint not null,
    "language_code" text not null,
    "title" text not null,
    "narrated_by" text,
    "description" text
);


alter table "public"."dua_infos" enable row level security;

create table "public"."dua_line_texts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "dua_line_id" bigint not null,
    "language_code" text not null,
    "text" text
);


alter table "public"."dua_line_texts" enable row level security;

create table "public"."dua_lines" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "dua_id" bigint not null,
    "line_number" bigint not null,
    "type" text not null,
    "end_of_section" boolean not null,
    "repetitions_number" bigint
);


alter table "public"."dua_lines" enable row level security;

create table "public"."dua_lines_has_recitations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "dua_line_id" bigint not null,
    "dua_recitation_id" bigint not null,
    "start_time_in_ms" bigint not null
);


alter table "public"."dua_lines_has_recitations" enable row level security;

create table "public"."dua_recitations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "dua_id" bigint not null,
    "reciter_id" bigint not null,
    "duration_in_ms" bigint not null,
    "audio_low_quality_url" text not null,
    "audio_high_quality_url" text not null,
    "shorten_to_ms" bigint
);


alter table "public"."dua_recitations" enable row level security;

create table "public"."dua_references" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "type" text not null,
    "url" text not null,
    "language_code" text not null,
    "dua_id" bigint
);


alter table "public"."dua_references" enable row level security;

create table "public"."duas" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "route_name" text not null,
    "background_image_low_quality_url" text not null,
    "background_image_high_quality_url" text not null,
    "popular" boolean not null,
    "type" text not null,
    "recommended_recitation_times" json not null
);


alter table "public"."duas" enable row level security;

create table "public"."languages" (
    "code" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
);


alter table "public"."languages" enable row level security;

create table "public"."reciters" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "full_name_tl" text not null,
    "full_name_ar" text,
    "profile_image_url" text
);


alter table "public"."reciters" enable row level security;

create table "public"."tags" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "name" text not null
);


alter table "public"."tags" enable row level security;

CREATE UNIQUE INDEX dua_has_tags_pkey ON public.dua_has_tags USING btree (dua_id, tag_id);

CREATE UNIQUE INDEX dua_info_pkey ON public.dua_infos USING btree (id);

CREATE UNIQUE INDEX dua_line_has_recitation_pkey ON public.dua_lines_has_recitations USING btree (id);

CREATE UNIQUE INDEX dua_line_texts_pkey ON public.dua_line_texts USING btree (id);

CREATE UNIQUE INDEX dua_lines_pkey ON public.dua_lines USING btree (id);

CREATE UNIQUE INDEX dua_recitation_pkey ON public.dua_recitations USING btree (id);

CREATE UNIQUE INDEX dua_references_pkey ON public.dua_references USING btree (id);

CREATE UNIQUE INDEX duas_pkey ON public.duas USING btree (id);

CREATE UNIQUE INDEX languages_pkey ON public.languages USING btree (code);

CREATE UNIQUE INDEX reciter_pkey ON public.reciters USING btree (id);

CREATE UNIQUE INDEX tags_pkey ON public.tags USING btree (id);

alter table "public"."dua_has_tags" add constraint "dua_has_tags_pkey" PRIMARY KEY using index "dua_has_tags_pkey";

alter table "public"."dua_infos" add constraint "dua_info_pkey" PRIMARY KEY using index "dua_info_pkey";

alter table "public"."dua_line_texts" add constraint "dua_line_texts_pkey" PRIMARY KEY using index "dua_line_texts_pkey";

alter table "public"."dua_lines" add constraint "dua_lines_pkey" PRIMARY KEY using index "dua_lines_pkey";

alter table "public"."dua_lines_has_recitations" add constraint "dua_line_has_recitation_pkey" PRIMARY KEY using index "dua_line_has_recitation_pkey";

alter table "public"."dua_recitations" add constraint "dua_recitation_pkey" PRIMARY KEY using index "dua_recitation_pkey";

alter table "public"."dua_references" add constraint "dua_references_pkey" PRIMARY KEY using index "dua_references_pkey";

alter table "public"."duas" add constraint "duas_pkey" PRIMARY KEY using index "duas_pkey";

alter table "public"."languages" add constraint "languages_pkey" PRIMARY KEY using index "languages_pkey";

alter table "public"."reciters" add constraint "reciter_pkey" PRIMARY KEY using index "reciter_pkey";

alter table "public"."tags" add constraint "tags_pkey" PRIMARY KEY using index "tags_pkey";

alter table "public"."dua_has_tags" add constraint "public_dua_has_tags_dua_id_fkey" FOREIGN KEY (dua_id) REFERENCES duas(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."dua_has_tags" validate constraint "public_dua_has_tags_dua_id_fkey";

alter table "public"."dua_has_tags" add constraint "public_dua_has_tags_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES tags(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."dua_has_tags" validate constraint "public_dua_has_tags_tag_id_fkey";

alter table "public"."dua_infos" add constraint "public_dua_info_dua_id_fkey" FOREIGN KEY (dua_id) REFERENCES duas(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."dua_infos" validate constraint "public_dua_info_dua_id_fkey";

alter table "public"."dua_infos" add constraint "public_dua_info_language_id_fkey" FOREIGN KEY (language_code) REFERENCES languages(code) not valid;

alter table "public"."dua_infos" validate constraint "public_dua_info_language_id_fkey";

alter table "public"."dua_line_texts" add constraint "public_dua_line_texts_dua_line_id_fkey" FOREIGN KEY (dua_line_id) REFERENCES dua_lines(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."dua_line_texts" validate constraint "public_dua_line_texts_dua_line_id_fkey";

alter table "public"."dua_line_texts" add constraint "public_dua_line_texts_language_id_fkey" FOREIGN KEY (language_code) REFERENCES languages(code) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."dua_line_texts" validate constraint "public_dua_line_texts_language_id_fkey";

alter table "public"."dua_lines" add constraint "public_dua_lines_dua_id_fkey" FOREIGN KEY (dua_id) REFERENCES duas(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."dua_lines" validate constraint "public_dua_lines_dua_id_fkey";

alter table "public"."dua_lines_has_recitations" add constraint "public_dua_line_has_recitation_dua_line_id_fkey" FOREIGN KEY (dua_line_id) REFERENCES dua_lines(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."dua_lines_has_recitations" validate constraint "public_dua_line_has_recitation_dua_line_id_fkey";

alter table "public"."dua_lines_has_recitations" add constraint "public_dua_lines_has_recitations_dua_recitation_id_fkey" FOREIGN KEY (dua_recitation_id) REFERENCES dua_recitations(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."dua_lines_has_recitations" validate constraint "public_dua_lines_has_recitations_dua_recitation_id_fkey";

alter table "public"."dua_recitations" add constraint "public_dua_recitation_dua_id_fkey" FOREIGN KEY (dua_id) REFERENCES duas(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."dua_recitations" validate constraint "public_dua_recitation_dua_id_fkey";

alter table "public"."dua_recitations" add constraint "public_dua_recitation_reciter_id_fkey" FOREIGN KEY (reciter_id) REFERENCES reciters(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."dua_recitations" validate constraint "public_dua_recitation_reciter_id_fkey";

alter table "public"."dua_references" add constraint "public_dua_references_dua_id_fkey" FOREIGN KEY (dua_id) REFERENCES duas(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."dua_references" validate constraint "public_dua_references_dua_id_fkey";

alter table "public"."dua_references" add constraint "public_dua_references_language_id_fkey" FOREIGN KEY (language_code) REFERENCES languages(code) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."dua_references" validate constraint "public_dua_references_language_id_fkey";

grant delete on table "public"."dua_has_tags" to "anon";

grant insert on table "public"."dua_has_tags" to "anon";

grant references on table "public"."dua_has_tags" to "anon";

grant select on table "public"."dua_has_tags" to "anon";

grant trigger on table "public"."dua_has_tags" to "anon";

grant truncate on table "public"."dua_has_tags" to "anon";

grant update on table "public"."dua_has_tags" to "anon";

grant delete on table "public"."dua_has_tags" to "authenticated";

grant insert on table "public"."dua_has_tags" to "authenticated";

grant references on table "public"."dua_has_tags" to "authenticated";

grant select on table "public"."dua_has_tags" to "authenticated";

grant trigger on table "public"."dua_has_tags" to "authenticated";

grant truncate on table "public"."dua_has_tags" to "authenticated";

grant update on table "public"."dua_has_tags" to "authenticated";

grant delete on table "public"."dua_has_tags" to "service_role";

grant insert on table "public"."dua_has_tags" to "service_role";

grant references on table "public"."dua_has_tags" to "service_role";

grant select on table "public"."dua_has_tags" to "service_role";

grant trigger on table "public"."dua_has_tags" to "service_role";

grant truncate on table "public"."dua_has_tags" to "service_role";

grant update on table "public"."dua_has_tags" to "service_role";

grant delete on table "public"."dua_infos" to "anon";

grant insert on table "public"."dua_infos" to "anon";

grant references on table "public"."dua_infos" to "anon";

grant select on table "public"."dua_infos" to "anon";

grant trigger on table "public"."dua_infos" to "anon";

grant truncate on table "public"."dua_infos" to "anon";

grant update on table "public"."dua_infos" to "anon";

grant delete on table "public"."dua_infos" to "authenticated";

grant insert on table "public"."dua_infos" to "authenticated";

grant references on table "public"."dua_infos" to "authenticated";

grant select on table "public"."dua_infos" to "authenticated";

grant trigger on table "public"."dua_infos" to "authenticated";

grant truncate on table "public"."dua_infos" to "authenticated";

grant update on table "public"."dua_infos" to "authenticated";

grant delete on table "public"."dua_infos" to "service_role";

grant insert on table "public"."dua_infos" to "service_role";

grant references on table "public"."dua_infos" to "service_role";

grant select on table "public"."dua_infos" to "service_role";

grant trigger on table "public"."dua_infos" to "service_role";

grant truncate on table "public"."dua_infos" to "service_role";

grant update on table "public"."dua_infos" to "service_role";

grant delete on table "public"."dua_line_texts" to "anon";

grant insert on table "public"."dua_line_texts" to "anon";

grant references on table "public"."dua_line_texts" to "anon";

grant select on table "public"."dua_line_texts" to "anon";

grant trigger on table "public"."dua_line_texts" to "anon";

grant truncate on table "public"."dua_line_texts" to "anon";

grant update on table "public"."dua_line_texts" to "anon";

grant delete on table "public"."dua_line_texts" to "authenticated";

grant insert on table "public"."dua_line_texts" to "authenticated";

grant references on table "public"."dua_line_texts" to "authenticated";

grant select on table "public"."dua_line_texts" to "authenticated";

grant trigger on table "public"."dua_line_texts" to "authenticated";

grant truncate on table "public"."dua_line_texts" to "authenticated";

grant update on table "public"."dua_line_texts" to "authenticated";

grant delete on table "public"."dua_line_texts" to "service_role";

grant insert on table "public"."dua_line_texts" to "service_role";

grant references on table "public"."dua_line_texts" to "service_role";

grant select on table "public"."dua_line_texts" to "service_role";

grant trigger on table "public"."dua_line_texts" to "service_role";

grant truncate on table "public"."dua_line_texts" to "service_role";

grant update on table "public"."dua_line_texts" to "service_role";

grant delete on table "public"."dua_lines" to "anon";

grant insert on table "public"."dua_lines" to "anon";

grant references on table "public"."dua_lines" to "anon";

grant select on table "public"."dua_lines" to "anon";

grant trigger on table "public"."dua_lines" to "anon";

grant truncate on table "public"."dua_lines" to "anon";

grant update on table "public"."dua_lines" to "anon";

grant delete on table "public"."dua_lines" to "authenticated";

grant insert on table "public"."dua_lines" to "authenticated";

grant references on table "public"."dua_lines" to "authenticated";

grant select on table "public"."dua_lines" to "authenticated";

grant trigger on table "public"."dua_lines" to "authenticated";

grant truncate on table "public"."dua_lines" to "authenticated";

grant update on table "public"."dua_lines" to "authenticated";

grant delete on table "public"."dua_lines" to "service_role";

grant insert on table "public"."dua_lines" to "service_role";

grant references on table "public"."dua_lines" to "service_role";

grant select on table "public"."dua_lines" to "service_role";

grant trigger on table "public"."dua_lines" to "service_role";

grant truncate on table "public"."dua_lines" to "service_role";

grant update on table "public"."dua_lines" to "service_role";

grant delete on table "public"."dua_lines_has_recitations" to "anon";

grant insert on table "public"."dua_lines_has_recitations" to "anon";

grant references on table "public"."dua_lines_has_recitations" to "anon";

grant select on table "public"."dua_lines_has_recitations" to "anon";

grant trigger on table "public"."dua_lines_has_recitations" to "anon";

grant truncate on table "public"."dua_lines_has_recitations" to "anon";

grant update on table "public"."dua_lines_has_recitations" to "anon";

grant delete on table "public"."dua_lines_has_recitations" to "authenticated";

grant insert on table "public"."dua_lines_has_recitations" to "authenticated";

grant references on table "public"."dua_lines_has_recitations" to "authenticated";

grant select on table "public"."dua_lines_has_recitations" to "authenticated";

grant trigger on table "public"."dua_lines_has_recitations" to "authenticated";

grant truncate on table "public"."dua_lines_has_recitations" to "authenticated";

grant update on table "public"."dua_lines_has_recitations" to "authenticated";

grant delete on table "public"."dua_lines_has_recitations" to "service_role";

grant insert on table "public"."dua_lines_has_recitations" to "service_role";

grant references on table "public"."dua_lines_has_recitations" to "service_role";

grant select on table "public"."dua_lines_has_recitations" to "service_role";

grant trigger on table "public"."dua_lines_has_recitations" to "service_role";

grant truncate on table "public"."dua_lines_has_recitations" to "service_role";

grant update on table "public"."dua_lines_has_recitations" to "service_role";

grant delete on table "public"."dua_recitations" to "anon";

grant insert on table "public"."dua_recitations" to "anon";

grant references on table "public"."dua_recitations" to "anon";

grant select on table "public"."dua_recitations" to "anon";

grant trigger on table "public"."dua_recitations" to "anon";

grant truncate on table "public"."dua_recitations" to "anon";

grant update on table "public"."dua_recitations" to "anon";

grant delete on table "public"."dua_recitations" to "authenticated";

grant insert on table "public"."dua_recitations" to "authenticated";

grant references on table "public"."dua_recitations" to "authenticated";

grant select on table "public"."dua_recitations" to "authenticated";

grant trigger on table "public"."dua_recitations" to "authenticated";

grant truncate on table "public"."dua_recitations" to "authenticated";

grant update on table "public"."dua_recitations" to "authenticated";

grant delete on table "public"."dua_recitations" to "service_role";

grant insert on table "public"."dua_recitations" to "service_role";

grant references on table "public"."dua_recitations" to "service_role";

grant select on table "public"."dua_recitations" to "service_role";

grant trigger on table "public"."dua_recitations" to "service_role";

grant truncate on table "public"."dua_recitations" to "service_role";

grant update on table "public"."dua_recitations" to "service_role";

grant delete on table "public"."dua_references" to "anon";

grant insert on table "public"."dua_references" to "anon";

grant references on table "public"."dua_references" to "anon";

grant select on table "public"."dua_references" to "anon";

grant trigger on table "public"."dua_references" to "anon";

grant truncate on table "public"."dua_references" to "anon";

grant update on table "public"."dua_references" to "anon";

grant delete on table "public"."dua_references" to "authenticated";

grant insert on table "public"."dua_references" to "authenticated";

grant references on table "public"."dua_references" to "authenticated";

grant select on table "public"."dua_references" to "authenticated";

grant trigger on table "public"."dua_references" to "authenticated";

grant truncate on table "public"."dua_references" to "authenticated";

grant update on table "public"."dua_references" to "authenticated";

grant delete on table "public"."dua_references" to "service_role";

grant insert on table "public"."dua_references" to "service_role";

grant references on table "public"."dua_references" to "service_role";

grant select on table "public"."dua_references" to "service_role";

grant trigger on table "public"."dua_references" to "service_role";

grant truncate on table "public"."dua_references" to "service_role";

grant update on table "public"."dua_references" to "service_role";

grant delete on table "public"."duas" to "anon";

grant insert on table "public"."duas" to "anon";

grant references on table "public"."duas" to "anon";

grant select on table "public"."duas" to "anon";

grant trigger on table "public"."duas" to "anon";

grant truncate on table "public"."duas" to "anon";

grant update on table "public"."duas" to "anon";

grant delete on table "public"."duas" to "authenticated";

grant insert on table "public"."duas" to "authenticated";

grant references on table "public"."duas" to "authenticated";

grant select on table "public"."duas" to "authenticated";

grant trigger on table "public"."duas" to "authenticated";

grant truncate on table "public"."duas" to "authenticated";

grant update on table "public"."duas" to "authenticated";

grant delete on table "public"."duas" to "service_role";

grant insert on table "public"."duas" to "service_role";

grant references on table "public"."duas" to "service_role";

grant select on table "public"."duas" to "service_role";

grant trigger on table "public"."duas" to "service_role";

grant truncate on table "public"."duas" to "service_role";

grant update on table "public"."duas" to "service_role";

grant delete on table "public"."languages" to "anon";

grant insert on table "public"."languages" to "anon";

grant references on table "public"."languages" to "anon";

grant select on table "public"."languages" to "anon";

grant trigger on table "public"."languages" to "anon";

grant truncate on table "public"."languages" to "anon";

grant update on table "public"."languages" to "anon";

grant delete on table "public"."languages" to "authenticated";

grant insert on table "public"."languages" to "authenticated";

grant references on table "public"."languages" to "authenticated";

grant select on table "public"."languages" to "authenticated";

grant trigger on table "public"."languages" to "authenticated";

grant truncate on table "public"."languages" to "authenticated";

grant update on table "public"."languages" to "authenticated";

grant delete on table "public"."languages" to "service_role";

grant insert on table "public"."languages" to "service_role";

grant references on table "public"."languages" to "service_role";

grant select on table "public"."languages" to "service_role";

grant trigger on table "public"."languages" to "service_role";

grant truncate on table "public"."languages" to "service_role";

grant update on table "public"."languages" to "service_role";

grant delete on table "public"."reciters" to "anon";

grant insert on table "public"."reciters" to "anon";

grant references on table "public"."reciters" to "anon";

grant select on table "public"."reciters" to "anon";

grant trigger on table "public"."reciters" to "anon";

grant truncate on table "public"."reciters" to "anon";

grant update on table "public"."reciters" to "anon";

grant delete on table "public"."reciters" to "authenticated";

grant insert on table "public"."reciters" to "authenticated";

grant references on table "public"."reciters" to "authenticated";

grant select on table "public"."reciters" to "authenticated";

grant trigger on table "public"."reciters" to "authenticated";

grant truncate on table "public"."reciters" to "authenticated";

grant update on table "public"."reciters" to "authenticated";

grant delete on table "public"."reciters" to "service_role";

grant insert on table "public"."reciters" to "service_role";

grant references on table "public"."reciters" to "service_role";

grant select on table "public"."reciters" to "service_role";

grant trigger on table "public"."reciters" to "service_role";

grant truncate on table "public"."reciters" to "service_role";

grant update on table "public"."reciters" to "service_role";

grant delete on table "public"."tags" to "anon";

grant insert on table "public"."tags" to "anon";

grant references on table "public"."tags" to "anon";

grant select on table "public"."tags" to "anon";

grant trigger on table "public"."tags" to "anon";

grant truncate on table "public"."tags" to "anon";

grant update on table "public"."tags" to "anon";

grant delete on table "public"."tags" to "authenticated";

grant insert on table "public"."tags" to "authenticated";

grant references on table "public"."tags" to "authenticated";

grant select on table "public"."tags" to "authenticated";

grant trigger on table "public"."tags" to "authenticated";

grant truncate on table "public"."tags" to "authenticated";

grant update on table "public"."tags" to "authenticated";

grant delete on table "public"."tags" to "service_role";

grant insert on table "public"."tags" to "service_role";

grant references on table "public"."tags" to "service_role";

grant select on table "public"."tags" to "service_role";

grant trigger on table "public"."tags" to "service_role";

grant truncate on table "public"."tags" to "service_role";

grant update on table "public"."tags" to "service_role";
