create table "public"."error_reports" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "dua_slug" text,
    "language_code" text,
    "line_number" text,
    "user_email" text,
    "error_description" text
);


alter table "public"."error_reports" enable row level security;

alter table "public"."dua_infos" drop column "narrated_by";

alter table "public"."duas" add column "slug" text not null;

update "public"."duas" set slug = route_name;

alter table "public"."duas" drop column "route_name";

CREATE UNIQUE INDEX duas_route_name_key ON public.duas USING btree (slug);

CREATE UNIQUE INDEX error_reports_pkey ON public.error_reports USING btree (id);

alter table "public"."error_reports" add constraint "error_reports_pkey" PRIMARY KEY using index "error_reports_pkey";

alter table "public"."duas" add constraint "duas_route_name_key" UNIQUE using index "duas_route_name_key";

grant delete on table "public"."error_reports" to "anon";

grant insert on table "public"."error_reports" to "anon";

grant references on table "public"."error_reports" to "anon";

grant select on table "public"."error_reports" to "anon";

grant trigger on table "public"."error_reports" to "anon";

grant truncate on table "public"."error_reports" to "anon";

grant update on table "public"."error_reports" to "anon";

grant delete on table "public"."error_reports" to "authenticated";

grant insert on table "public"."error_reports" to "authenticated";

grant references on table "public"."error_reports" to "authenticated";

grant select on table "public"."error_reports" to "authenticated";

grant trigger on table "public"."error_reports" to "authenticated";

grant truncate on table "public"."error_reports" to "authenticated";

grant update on table "public"."error_reports" to "authenticated";

grant delete on table "public"."error_reports" to "service_role";

grant insert on table "public"."error_reports" to "service_role";

grant references on table "public"."error_reports" to "service_role";

grant select on table "public"."error_reports" to "service_role";

grant trigger on table "public"."error_reports" to "service_role";

grant truncate on table "public"."error_reports" to "service_role";

grant update on table "public"."error_reports" to "service_role";

create policy "Enable insert for all users"
on "public"."error_reports"
as permissive
for insert
to public
with check (true);



