create table "public"."collection_has_duas" (
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "dua_id" bigint not null,
    "collection_id" bigint not null,
    "position" bigint
);


alter table "public"."collection_has_duas" enable row level security;

create table "public"."collection_translations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "title" text,
    "description" text,
    "seo_description" text,
    "language_code" text,
    "collection_id" bigint not null
);


alter table "public"."collection_translations" enable row level security;

create table "public"."collections" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "slug" text not null,
    "image_url" text,
    "page_views" bigint not null default '0'::bigint,
    "api_calls" bigint not null default '0'::bigint,
    "type" text
);


alter table "public"."collections" enable row level security;

create table "public"."post_translations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "post_id" bigint not null,
    "language_code" text not null,
    "slug" text not null,
    "excerpt" text not null,
    "body_markdown" text not null
);


alter table "public"."post_translations" enable row level security;

create table "public"."posts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "cover_image_url" text
);


alter table "public"."posts" enable row level security;

CREATE UNIQUE INDEX collection_has_duas_pkey ON public.collection_has_duas USING btree (dua_id, collection_id);

CREATE UNIQUE INDEX collection_translations_pkey ON public.collection_translations USING btree (id);

CREATE UNIQUE INDEX collections_pkey ON public.collections USING btree (id);

CREATE UNIQUE INDEX collections_slug_key ON public.collections USING btree (slug);

CREATE UNIQUE INDEX post_translations_pkey ON public.post_translations USING btree (id);

CREATE UNIQUE INDEX post_translations_slug_key ON public.post_translations USING btree (slug);

CREATE UNIQUE INDEX posts_pkey ON public.posts USING btree (id);

alter table "public"."collection_has_duas" add constraint "collection_has_duas_pkey" PRIMARY KEY using index "collection_has_duas_pkey";

alter table "public"."collection_translations" add constraint "collection_translations_pkey" PRIMARY KEY using index "collection_translations_pkey";

alter table "public"."collections" add constraint "collections_pkey" PRIMARY KEY using index "collections_pkey";

alter table "public"."post_translations" add constraint "post_translations_pkey" PRIMARY KEY using index "post_translations_pkey";

alter table "public"."posts" add constraint "posts_pkey" PRIMARY KEY using index "posts_pkey";

alter table "public"."collection_has_duas" add constraint "collection_has_duas_collection_id_fkey" FOREIGN KEY (collection_id) REFERENCES collections(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."collection_has_duas" validate constraint "collection_has_duas_collection_id_fkey";

alter table "public"."collection_has_duas" add constraint "collection_has_duas_dua_id_fkey" FOREIGN KEY (dua_id) REFERENCES duas(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."collection_has_duas" validate constraint "collection_has_duas_dua_id_fkey";

alter table "public"."collection_translations" add constraint "collection_translations_collection_id_fkey" FOREIGN KEY (collection_id) REFERENCES collections(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."collection_translations" validate constraint "collection_translations_collection_id_fkey";

alter table "public"."collection_translations" add constraint "collection_translations_language_code_fkey" FOREIGN KEY (language_code) REFERENCES languages(code) ON UPDATE CASCADE not valid;

alter table "public"."collection_translations" validate constraint "collection_translations_language_code_fkey";

alter table "public"."collections" add constraint "collections_slug_key" UNIQUE using index "collections_slug_key";

alter table "public"."post_translations" add constraint "post_translations_language_code_fkey" FOREIGN KEY (language_code) REFERENCES languages(code) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."post_translations" validate constraint "post_translations_language_code_fkey";

alter table "public"."post_translations" add constraint "post_translations_post_id_fkey" FOREIGN KEY (post_id) REFERENCES posts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."post_translations" validate constraint "post_translations_post_id_fkey";

alter table "public"."post_translations" add constraint "post_translations_slug_key" UNIQUE using index "post_translations_slug_key";

grant delete on table "public"."collection_has_duas" to "anon";

grant insert on table "public"."collection_has_duas" to "anon";

grant references on table "public"."collection_has_duas" to "anon";

grant select on table "public"."collection_has_duas" to "anon";

grant trigger on table "public"."collection_has_duas" to "anon";

grant truncate on table "public"."collection_has_duas" to "anon";

grant update on table "public"."collection_has_duas" to "anon";

grant delete on table "public"."collection_has_duas" to "authenticated";

grant insert on table "public"."collection_has_duas" to "authenticated";

grant references on table "public"."collection_has_duas" to "authenticated";

grant select on table "public"."collection_has_duas" to "authenticated";

grant trigger on table "public"."collection_has_duas" to "authenticated";

grant truncate on table "public"."collection_has_duas" to "authenticated";

grant update on table "public"."collection_has_duas" to "authenticated";

grant delete on table "public"."collection_has_duas" to "service_role";

grant insert on table "public"."collection_has_duas" to "service_role";

grant references on table "public"."collection_has_duas" to "service_role";

grant select on table "public"."collection_has_duas" to "service_role";

grant trigger on table "public"."collection_has_duas" to "service_role";

grant truncate on table "public"."collection_has_duas" to "service_role";

grant update on table "public"."collection_has_duas" to "service_role";

grant delete on table "public"."collection_translations" to "anon";

grant insert on table "public"."collection_translations" to "anon";

grant references on table "public"."collection_translations" to "anon";

grant select on table "public"."collection_translations" to "anon";

grant trigger on table "public"."collection_translations" to "anon";

grant truncate on table "public"."collection_translations" to "anon";

grant update on table "public"."collection_translations" to "anon";

grant delete on table "public"."collection_translations" to "authenticated";

grant insert on table "public"."collection_translations" to "authenticated";

grant references on table "public"."collection_translations" to "authenticated";

grant select on table "public"."collection_translations" to "authenticated";

grant trigger on table "public"."collection_translations" to "authenticated";

grant truncate on table "public"."collection_translations" to "authenticated";

grant update on table "public"."collection_translations" to "authenticated";

grant delete on table "public"."collection_translations" to "service_role";

grant insert on table "public"."collection_translations" to "service_role";

grant references on table "public"."collection_translations" to "service_role";

grant select on table "public"."collection_translations" to "service_role";

grant trigger on table "public"."collection_translations" to "service_role";

grant truncate on table "public"."collection_translations" to "service_role";

grant update on table "public"."collection_translations" to "service_role";

grant delete on table "public"."collections" to "anon";

grant insert on table "public"."collections" to "anon";

grant references on table "public"."collections" to "anon";

grant select on table "public"."collections" to "anon";

grant trigger on table "public"."collections" to "anon";

grant truncate on table "public"."collections" to "anon";

grant update on table "public"."collections" to "anon";

grant delete on table "public"."collections" to "authenticated";

grant insert on table "public"."collections" to "authenticated";

grant references on table "public"."collections" to "authenticated";

grant select on table "public"."collections" to "authenticated";

grant trigger on table "public"."collections" to "authenticated";

grant truncate on table "public"."collections" to "authenticated";

grant update on table "public"."collections" to "authenticated";

grant delete on table "public"."collections" to "service_role";

grant insert on table "public"."collections" to "service_role";

grant references on table "public"."collections" to "service_role";

grant select on table "public"."collections" to "service_role";

grant trigger on table "public"."collections" to "service_role";

grant truncate on table "public"."collections" to "service_role";

grant update on table "public"."collections" to "service_role";

grant delete on table "public"."post_translations" to "anon";

grant insert on table "public"."post_translations" to "anon";

grant references on table "public"."post_translations" to "anon";

grant select on table "public"."post_translations" to "anon";

grant trigger on table "public"."post_translations" to "anon";

grant truncate on table "public"."post_translations" to "anon";

grant update on table "public"."post_translations" to "anon";

grant delete on table "public"."post_translations" to "authenticated";

grant insert on table "public"."post_translations" to "authenticated";

grant references on table "public"."post_translations" to "authenticated";

grant select on table "public"."post_translations" to "authenticated";

grant trigger on table "public"."post_translations" to "authenticated";

grant truncate on table "public"."post_translations" to "authenticated";

grant update on table "public"."post_translations" to "authenticated";

grant delete on table "public"."post_translations" to "service_role";

grant insert on table "public"."post_translations" to "service_role";

grant references on table "public"."post_translations" to "service_role";

grant select on table "public"."post_translations" to "service_role";

grant trigger on table "public"."post_translations" to "service_role";

grant truncate on table "public"."post_translations" to "service_role";

grant update on table "public"."post_translations" to "service_role";

grant delete on table "public"."posts" to "anon";

grant insert on table "public"."posts" to "anon";

grant references on table "public"."posts" to "anon";

grant select on table "public"."posts" to "anon";

grant trigger on table "public"."posts" to "anon";

grant truncate on table "public"."posts" to "anon";

grant update on table "public"."posts" to "anon";

grant delete on table "public"."posts" to "authenticated";

grant insert on table "public"."posts" to "authenticated";

grant references on table "public"."posts" to "authenticated";

grant select on table "public"."posts" to "authenticated";

grant trigger on table "public"."posts" to "authenticated";

grant truncate on table "public"."posts" to "authenticated";

grant update on table "public"."posts" to "authenticated";

grant delete on table "public"."posts" to "service_role";

grant insert on table "public"."posts" to "service_role";

grant references on table "public"."posts" to "service_role";

grant select on table "public"."posts" to "service_role";

grant trigger on table "public"."posts" to "service_role";

grant truncate on table "public"."posts" to "service_role";

grant update on table "public"."posts" to "service_role";

create policy "Enable read access for all users"
on "public"."collection_has_duas"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."collection_translations"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."collections"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."post_translations"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."posts"
as permissive
for select
to public
using (true);



